dataset: CML_Polish
path:
  corpus_path: ../cml-tts/train/
  preprocessed_path: "../output_dataset/preprocessed_data/CML_Polish"
  raw_path: ../output_dataset/raw_data
preprocessing:
  audio:
    max_wav_value: 32768.0
    sampling_rate: 22050
  energy:
    feature: phoneme_level
    normalization: true
  mel:
    mel_fmax: 8000
    mel_fmin: 0
    n_mel_channels: 80
  pitch:
    feature: phoneme_level
    normalization: true
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  text:
    language: en
    max_length: 4096
    text_cleaners: []
  val_size: 512
